class AppEn {
  static Map<String, String> values = {
    // Auth
    "login": "Login",
    "unique_id": "Unique ID",
    "password": "Password",
    "school_login": "School Login",
    "please_enter_id_password": "Please enter ID and Password",
    "login_successful": "Login Successful",
    "invalid_id_password": "Invalid ID or Password",
    
    // Dashboards
    "zp_school": "ZP SCHOOL MANDAVE KH",
    "zp_school_short": "ZP SCHOOL",
    "zp_school_system": "ZP SCHOOL SYSTEM",
    "teacher_dashboard": "Teacher Dashboard",
    "admin_dashboard": "Admin Dashboard",
    "superadmin_dashboard": "Super Admin Dashboard",
    "student_dashboard": "Student Dashboard",
    "student_space": "Student Space",
    
    // Navigation / Tabs
    "home": "Home",
    "dashboard": "Dashboard",
    "students": "Students",
    "teachers": "Teachers",
    "profile": "Profile",
    "books": "Books",
    "attendance": "Attendance",
    "homework": "Homework",
    "results": "Results",
    "logout": "Logout",
    "schools": "Schools",
    "reports": "Reports",
    "system_settings": "System Settings",

    // Roles
    "welcome_teacher": "Welcome Teacher",
    "welcome_admin": "Welcome Admin",
    "welcome_superadmin": "Welcome Super Admin",
    "welcome_student": "Welcome Student",
    "administrator": "Administrator",
    "super_administrator": "Super Administrator",
    "class_teacher": "Class Teacher",

    // Dashboard Items
    "overview": "Overview",
    "total_students": "Total Students",
    "present": "Present",
    "absent": "Absent",
    "other": "Other",
    "switch_class": "Switch Class",
    "current": "Current",
    "exams": "Exams",
    "my_complaints": "My Complaints",
    "school_information": "School Information",
    
    // Greetings
    "good_morning": "Good Morning",
    "good_afternoon": "Good Afternoon",
    "good_evening": "Good Evening",
    "good_night": "Good Night",
    
    // Dialogs
    "are_you_sure_logout": "Are you sure you want to logout?",
    "cancel": "Cancel",
    "language": "Language",

    // Admin Dashboard
    "school_overview": "School Overview",
    "quick_actions": "Quick Actions",
    "add_student": "Add Student",
    "add_teacher": "Add Teacher",
    "complaints": "Complaints",
    "select_class": "Select Class",
    "choose_class_add_student": "Choose a class to add a new student",
    "change": "Change",
    "class_label": "Class",

    // Students & Teachers Directory
    "student_directory": "Student Directory",
    "faculty_directory": "Faculty Directory",
    "total_staff": "Total Staff",
    "no_teachers_found": "No teachers found",
    "no_students_found": "No students found",
    "staff": "Staff",
    "remove_staff": "Remove Staff",
    
    // Profile & Info
    "failed_to_load_profile": "Failed to load profile",
    "personal_details": "Personal Details",
    "phone": "Phone",
    "professional_hub": "Professional Hub",
    "years": "years",
    "joined_date": "Joined Date",
    "school_administrator": "School Administrator",
    "logout_securely": "Logout Securely",

    // Notices
    "school_notices": "School Notices",
    "filter_by_date": "Filter by Date",
    "clear_filter": "Clear Filter",
    "no_notices_found": "No notices found",
    "everyone": "Everyone",
    "all_students": "All Students",
    "date": "Date",
    "sent_to": "Sent To",
    "created_by": "Created By",
    "created_at": "Created At",
    "close": "Close",
    "delete_notice": "Delete Notice",
    "are_you_sure_delete_notice": "Are you sure you want to delete this notice?",
    "notice_deleted_success": "Notice deleted successfully",
    "notice_deleted_failed": "Failed to delete notice",
    "edit_notice": "Edit Notice",
    "send_notice": "Send Notice",
    "notice_details": "Notice Details",
    "title_required": "Title *",
    "description_required": "Description *",
    "notice_date_required": "Notice Date *",
    "required": "Required",
    "recipients": "Recipients",
    "select_class_optional": "Select Class (Optional)",
    "all_classes": "All Classes",
    "update_notice": "Update Notice",
    "notice_updated_success": "Notice updated successfully",
    "notice_updated_failed": "Failed to update notice",
    "notice_sent_success": "Notice sent successfully",
    "notice_sent_failed": "Failed to send notice",

    "no_books_available": "No books available",
    "add_new_book": "Add New Book",
    "filter_by_class": "Filter by Class",
    "no_internet_connection": "No internet connection. Please check your network.",
    "failed_to_load_books": "Failed to load books. Please try again.",
    "delete_book": "Delete Book",
    "are_you_sure_delete_book": "Are you sure you want to delete this book?",
    "book_deleted_success": "Book Deleted Successfully",
    "book_deleted_failed": "Failed to Delete Book",
    "downloaded": "Downloaded:",
    "download_failed": "Download failed",
    "book_url_not_available": "Book URL not available",
    "failed_to_open_book": "Failed to open book",
    "retry": "Retry",
    "unknown": "Unknown",
    "subject": "Subject",
    "please_select_class": "Please select a class",
    "please_select_pdf": "Please select a PDF file",
    "failed_to_upload_file": "Failed to upload file",
    "book_added_success": "Book Added Successfully",
    "book_added_failed": "Failed to Add Book",
    "book_name": "Book Name",
    "subject_name": "Subject Name",
    "select_pdf_file": "Select PDF File",
    "add_book": "Add Book",

    // Teachers Form
    "add_new_teacher": "Add New Teacher",
    "edit_teacher_profile": "Edit Teacher Profile",
    "personal_details": "Personal Details",
    "professional_details": "Professional Details",
    "account_and_assignment": "Account & Assignment",
    "contact_class_assignment": "Contact & Class Assignment",
    "first_name": "First Name *",
    "middle_name": "Middle Name",
    "last_name": "Last Name *",
    "gender_required": "Gender *",
    "male": "male",
    "female": "female",
    "designation_required": "Designation *",
    "qualification_required": "Qualification *",
    "experience_years": "Experience (Years)",
    "mobile_number_required": "Mobile Number *",
    "login_password_required": "Login Password *",
    "is_class_teacher": "Is Class Teacher?",
    "assign_primary_class": "Assign a primary class to this teacher",
    "assigned_class": "Assigned Class",
    "division": "Division",
    "register_teacher": "Register Teacher",
    "update_teacher": "Update Teacher",
    "success": "Success!",
    "teacher_registered_success": "Teacher registered successfully!",
    "teacher_updated_success": "Teacher updated successfully",
    "teacher_updated_failed": "Failed to update teacher",
    "teacher_added_failed": "Failed to add teacher",
    "unique_id_label": "UNIQUE ID",
    "select_date": "Select Date",

    "student_profile": "Student Profile",
    "teacher_profile": "Teacher Profile",
    "call_parent": "Call Parent",
    "call": "Call",
    "edit": "Edit",
    "delete": "Delete",
    "academic_information": "Academic Information",
    "professional_information": "Professional Information",
    "student_id": "Student ID",
    "staff_id": "Staff ID",
    "gr_number": "G.R. Number",
    "roll_number": "Roll Number",
    "admission_date": "Admission Date",
    "category": "Category",
    "personal_information": "Personal Information",
    "aadhar_number": "Aadhar Number",
    "gender": "Gender",
    "date_of_birth": "Date of Birth",
    "parent_contact_details": "Parent & Contact Details",
    "father_parent_name": "Father/Parent Name",
    "mothers_name": "Mother's Name",
    "mobile": "Mobile",
    "address": "Address",
    "qualification": "Qualification",
    "experience": "Experience",
    "joining_date": "Joining Date",
    "class_responsibility": "Class Responsibility",
    
    // Actions & Messages
    "view_profile": "View Profile",
    "edit_student": "Edit Student",
    "delete_student": "Delete Student",
    "delete_teacher": "Delete Teacher",
    "are_you_sure_delete": "Are you sure you want to delete",
    "teacher_deleted_success": "Teacher deleted successfully",
    "teacher_deleted_failed": "Failed to delete teacher",
    "student_deleted_success": "Student deleted successfully",
    "student_deleted_failed": "Failed to delete student",
    "not_specified": "Not specified",
    "total": "Total",
    "notices": "Notices"
  };
}
