class AppMr {
  static Map<String, String> values = {
    // Auth
    "login": "लॉगिन",
    "unique_id": "युनिक आयडी",
    "password": "पासवर्ड",
    "school_login": "शाळा लॉगिन",
    "please_enter_id_password": "कृपया आयडी आणि पासवर्ड टाका",
    "login_successful": "लॉगिन यशस्वी",
    "invalid_id_password": "चुकीची आयडी किंवा पासवर्ड",
    
    // Dashboards
    "zp_school": "जि. प. शाळा मांडवे खु.",
    "zp_school_short": "जि. प. शाळा",
    "zp_school_system": "जि. प. शाळा प्रणाली",
    "teacher_dashboard": "शिक्षक डॅशबोर्ड",
    "admin_dashboard": "प्रशासक डॅशबोर्ड",
    "superadmin_dashboard": "सुपर प्रशासक डॅशबोर्ड",
    "student_dashboard": "विद्यार्थी डॅशबोर्ड",
    "student_space": "विद्यार्थी विभाग",
    
    // Navigation / Tabs
    "home": "मुख्यपृष्ठ",
    "dashboard": "डॅशबोर्ड",
    "students": "विद्यार्थी",
    "teachers": "शिक्षक",
    "profile": "प्रोफाईल",
    "books": "पुस्तके",
    "attendance": "हजेरी",
    "homework": "गृहपाठ",
    "results": "निकाल",
    "logout": "लॉगआऊट",
    "schools": "शाळा",
    "reports": "अहवाल",
    "system_settings": "प्रणाली सेटिंग्ज",

    // Roles
    "welcome_teacher": "शिक्षकांचे स्वागत आहे",
    "welcome_admin": "प्रशासकांचे स्वागत आहे",
    "welcome_superadmin": "सुपर प्रशासकांचे स्वागत आहे",
    "welcome_student": "विद्यार्थ्यांचे स्वागत आहे",
    "administrator": "प्रशासक",
    "super_administrator": "सुपर प्रशासक",
    "class_teacher": "वर्गशिक्षक",

    // Dashboard Items
    "overview": "आढावा",
    "total_students": "एकूण विद्यार्थी",
    "present": "उपस्थित",
    "absent": "अनुपस्थित",
    "other": "इतर",
    "switch_class": "वर्ग बदला",
    "current": "सध्याचे",
    "exams": "परीक्षा",
    "my_complaints": "माझी तक्रार",
    "school_information": "शाळेची माहिती",
    
    // Greetings
    "good_morning": "शुभ सकाळ",
    "good_afternoon": "शुभ दुपार",
    "good_evening": "शुभ संध्याकाळ",
    "good_night": "शुभ रात्री",
    
    // Dialogs
    "are_you_sure_logout": "तुम्हाला नक्की लॉगआऊट करायचे आहे का?",
    "cancel": "रद्द करा",
    "language": "भाषा",

    // Admin Dashboard
    "school_overview": "शाळेचा आढावा",
    "quick_actions": "जलद कृती",
    "add_student": "विद्यार्थी जोडा",
    "add_teacher": "शिक्षक जोडा",
    "complaints": "तक्रारी",
    "select_class": "वर्ग निवडा",
    "choose_class_add_student": "नवीन विद्यार्थी जोडण्यासाठी वर्ग निवडा",
    "change": "बदला",
    "class_label": "वर्ग",

    // Students & Teachers Directory
    "student_directory": "विद्यार्थी यादी",
    "faculty_directory": "शिक्षक यादी",
    "total_staff": "एकूण कर्मचारी",
    "no_teachers_found": "कोणतेही शिक्षक आढळले नाहीत",
    "no_students_found": "कोणतेही विद्यार्थी आढळले नाहीत",
    "staff": "कर्मचारी",
    "remove_staff": "कर्मचाऱ्यास काढा",
    
    // Profile & Info
    "failed_to_load_profile": "प्रोफाईल लोड करण्यात अयशस्वी",
    "personal_details": "वैयक्तिक तपशील",
    "phone": "फोन",
    "professional_hub": "व्यावसायिक माहिती",
    "years": "वर्षे",
    "joined_date": "रुजू झालेली तारीख",
    "school_administrator": "शाळा प्रशासक",
    "logout_securely": "सुरक्षितपणे लॉगआऊट करा",

    // Notices
    "school_notices": "शाळेच्या सूचना",
    "filter_by_date": "तारखेनुसार फिल्टर करा",
    "clear_filter": "फिल्टर काढा",
    "no_notices_found": "कोणत्याही सूचना आढळल्या नाहीत",
    "everyone": "सर्वजण",
    "all_students": "सर्व विद्यार्थी",
    "date": "तारीख",
    "sent_to": "कोणाला पाठवले",
    "created_by": "निर्मिती",
    "created_at": "तयार केल्याची वेळ",
    "close": "बंद करा",
    "delete_notice": "सूचना काढून टाका",
    "are_you_sure_delete_notice": "तुम्हाला नक्की ही सूचना काढून टाकायची आहे का?",
    "notice_deleted_success": "सूचना यशस्वीरित्या काढण्यात आली",
    "notice_deleted_failed": "सूचना काढण्यास अयशस्वी",
    "edit_notice": "सूचना संपादित करा",
    "send_notice": "सूचना पाठवा",
    "notice_details": "सूचनेचे तपशील",
    "title_required": "शीर्षक *",
    "description_required": "वर्णन *",
    "notice_date_required": "सूचनेची तारीख *",
    "required": "आवश्यक",
    "recipients": "प्राप्तकर्ते",
    "select_class_optional": "वर्ग निवडा (वैकल्पिक)",
    "all_classes": "सर्व वर्ग",
    "update_notice": "सूचना अद्ययावत करा",
    "notice_updated_success": "सूचना यशस्वीरित्या अद्ययावत झाली",
    "notice_updated_failed": "सूचना अद्ययावत करण्यास अयशस्वी",
    "notice_sent_success": "सूचना यशस्वीरित्या पाठवली",
    "notice_sent_failed": "सूचना पाठविण्यास अयशस्वी",

    "no_books_available": "कोणतीही पुस्तके उपलब्ध नाहीत",
    "add_new_book": "नवीन पुस्तक जोडा",
    "filter_by_class": "वर्गावरून फिल्टर करा",
    "no_internet_connection": "इंटरनेट कनेक्शन नाही. कृपया तुमचे नेटवर्क तपासा.",
    "failed_to_load_books": "पुस्तके लोड करण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
    "delete_book": "पुस्तक काढून टाका",
    "are_you_sure_delete_book": "तुम्हाला नक्की हे पुस्तक काढून टाकायचे आहे का?",
    "book_deleted_success": "पुस्तक यशस्वीरित्या काढण्यात आले",
    "book_deleted_failed": "पुस्तक काढण्यास अयशस्वी",
    "downloaded": "डाउनलोड केले:",
    "download_failed": "डाउनलोड अयशस्वी",
    "book_url_not_available": "पुस्तकाची लिंक उपलब्ध नाही",
    "failed_to_open_book": "पुस्तक उघडण्यात अयशस्वी",
    "retry": "पुन्हा प्रयत्न करा",
    "unknown": "अज्ञात",
    "subject": "विषय",
    "please_select_class": "कृपया वर्ग निवडा",
    "please_select_pdf": "कृपया पीडीएफ(PDF) फाइल निवडा",
    "failed_to_upload_file": "फाइल अपलोड करण्यात अयशस्वी",
    "book_added_success": "पुस्तक यशस्वीरित्या जोडले",
    "book_added_failed": "पुस्तक जोडण्यास अयशस्वी",
    "book_name": "पुस्तकाचे नाव",
    "subject_name": "विषयाचे नाव",
    "select_pdf_file": "पीडीएफ(PDF) फाइल निवडा",
    "add_book": "पुस्तक जोडा",

    // Teachers Form
    "add_new_teacher": "नवीन शिक्षक जोडा",
    "edit_teacher_profile": "शिक्षक प्रोफाईल संपादित करा",
    "professional_details": "व्यावसायिक तपशील",
    "account_and_assignment": "खाते आणि वर्ग नेमणूक",
    "contact_class_assignment": "संपर्क आणि वर्ग नेमणूक",
    "first_name": "प्रथम नाव *",
    "middle_name": "मधले नाव",
    "last_name": "आडनाव *",
    "gender_required": "लिंग *",
    "male": "पुरुष",
    "female": "स्त्री",
    "designation_required": "पद *",
    "qualification_required": "शिक्षण *",
    "experience_years": "अनुभव (वर्षे)",
    "mobile_number_required": "मोबाईल नंबर *",
    "login_password_required": "लॉगिन पासवर्ड *",
    "is_class_teacher": "वर्गशिक्षक आहेत का?",
    "assign_primary_class": "या शिक्षकाला प्राथमिक वर्ग नियुक्त करा",
    "assigned_class": "नियुक्त केलेला वर्ग",
    "division": "तुकडी",
    "register_teacher": "शिक्षक नोंदणी करा",
    "update_teacher": "शिक्षक माहिती अद्ययावत करा",
    "success": "यशस्वी!",
    "teacher_registered_success": "शिक्षकांची नोंदणी यशस्वीरित्या झाली!",
    "teacher_updated_success": "शिक्षक माहिती यशस्वीरित्या अद्यतित केली",
    "teacher_updated_failed": "शिक्षक माहिती अद्यतित करण्यात अयशस्वी",
    "teacher_added_failed": "शिक्षक जोडण्यात अयशस्वी",
    "unique_id_label": "युनिक आयडी",
    "select_date": "तारीख निवडा",

    "student_profile": "विद्यार्थी प्रोफाईल",
    "teacher_profile": "शिक्षक प्रोफाईल",
    "call_parent": "पालकांना कॉल करा",
    "call": "कॉल करा",
    "edit": "संपादित करा",
    "delete": "काढून टाका",
    "academic_information": "शैक्षणिक माहिती",
    "professional_information": "व्यावसायिक माहिती",
    "student_id": "विद्यार्थी आयडी",
    "staff_id": "कर्मचारी आयडी",
    "gr_number": "जी.आर. क्रमांक",
    "roll_number": "हजेरी क्रमांक",
    "admission_date": "प्रवेश दिनांक",
    "category": "प्रवर्ग",
    "personal_information": "वैयक्तिक माहिती",
    "aadhar_number": "आधार क्रमांक",
    "gender": "लिंग",
    "date_of_birth": "जन्म तारीख",
    "parent_contact_details": "पालक आणि संपर्क तपशील",
    "father_parent_name": "वडिलांचे/पालकांचे नाव",
    "mothers_name": "आईचे नाव",
    "mobile": "मोबाईल",
    "address": "पत्ता",
    "qualification": "शिक्षण",
    "experience": "अनुभव",
    "joining_date": "रुजू होण्याची तारीख",
    "class_responsibility": "वर्ग जबाबदारी",
    
    // Actions & Messages
    "view_profile": "प्रोफाईल पहा",
    "edit_student": "विद्यार्थी संपादित करा",
    "delete_student": "विद्यार्थी काढून टाका",
    "delete_teacher": "शिक्षक काढून टाका",
    "are_you_sure_delete": "तुम्हाला नक्की काढून टाकायचे आहे का",
    "teacher_deleted_success": "शिक्षक यशस्वीरित्या काढण्यात आले",
    "teacher_deleted_failed": "शिक्षक काढण्यात अयशस्वी",
    "student_deleted_success": "विद्यार्थी यशस्वीरित्या काढण्यात आला",
    "student_deleted_failed": "विद्यार्थी काढण्यात अयशस्वी",
    "not_specified": "नमूद केलेले नाही",
    "total": "एकूण",
    "notices": "सूचना"
  };
}
